### ISSUE TITLE
npm run dev error

### ISSUE THREAD

**Issue by alexXiaoMing** [emqtt/EMQ-Android-Toolkit#1]
npm install && npm run dev 

ERROR in ./~/buble-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./s
rc/App.vue
Module not found: Error: Can't resolve 'dateformat' in 'D:\workspaces\nodejs\EMQ
-Web-Toolkit\src'
 @ ./~/buble-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./src/App
.vue 100:0-35
 @ ./src/App.vue
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://127.0.0.1:8082 webpack/hot/dev-serve
r ./src/main.js

**Comment by Zhiw** [comment]
I think you are in the wrong place,you can see [EMQ-Web-Toolkit](https://github.com/emqtt/EMQ-Web-Toolkit)
